"""Initial migration

Revision ID: b02ae5c78a9b
Revises: 
Create Date: 2022-06-22 18:24:14.296468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02ae5c78a9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date_created', sa.Date(), nullable=True))
    op.add_column('posts', sa.Column('date_modified', sa.Date(), nullable=True))
    op.drop_column('posts', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_column('posts', 'date_modified')
    op.drop_column('posts', 'date_created')
    # ### end Alembic commands ###
